project:
  type: book
  output-dir: docs #docs _book

book:
  title: "Taller de Cómputo"
  site-url: https://github.com/EveliaCoss/Mt2026_Taller_Computo_libro
  page-footer:  "Taller de Cómputo, 1er semestre: Dra. Evelia Coss" 
  sidebar: 
    # background: "#ffcccc"
    logo: "flyer/logo_enes.png" # Logo ENES
    search: true
  author: 
    - name: Evelia Coss
      degrees: PhD
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: Mexico
          url: https://www.enesjuriquilla.unam.mx/
  
  date: "07/08/2026"
  page-navigation: true        # Provide next and previous article links in footer
  back-to-top-navigation: true # Provide a ‘back to top’ navigation button
  chapters:
    - index.qmd
    - temario.qmd
    - cap1A.qmd
    - cap1B.qmd
    - cap2.qmd
    - cap3.qmd  # Buenas practicas en programacion    
    - part: "**Pre-requisitos**"
      chapters: 
        - install_B.qmd # Instalación de Git y Bash
        - install_R.qmd # Instalación de R y RStudio    
        - install_git.qmd # Instalación Git y Bash
    - part: "**Sección 1** - Introducción a Bash"
      chapters: 
        - cap4.qmd  # Introducción a Linux/Unix
        - cap5.qmd  # Mis primeros pasos en Bash   
        - cap6.qmd  # Wildcards y Streams
    - part: "**Sección 2** - Edición de archivos con Bash"
      chapters:     
        - cap7.qmd  # Operadores de redirección de datos I/O
        - cap8.qmd  # Edición de archivos con los editores de texto (nano y vim)
        - cap9.qmd  # Edición de archivos con el editor de flujo sed
        - cap10.qmd # Enlaces simbólicos (symlinks)
        - cap11.qmd # Filtrado de texto (grep, cut, sort, uniq, wc)
        - cap12.qmd # Condicionales
        - cap13.qmd # Scripts en Bash
        - cap14.qmd # Bucles (for loops)
    - part: "**Sección 3** - Introducción a Git/GitHub"
      chapters:  
        - cap15.qmd # Intro a Git
        - cap16.qmd # Configurar git
        - cap17.qmd # Crear e inicializar repos
        - cap18.qmd # Rastrear cambios
        - cap19.qmd # Explorando el historial
        - cap20.qmd # Restore y reset
        - cap21.qmd # Ignorar archivos
    - part: "**Sección 4** - Conexión con Github"
      chapters:
        - cap22.qmd # Conexión con Github
        - cap23.qmd # Trabajando con colaboradores
        - cap24.qmd # Resolviendo conflictos
        - cap25.qmd # Trabajando con ramas
        - cap26.qmd # Conexión RStudio con Git 
        - cap27.qmd # Resumen y practica final        
    - part: "**Sección 5** - Introducción a R y Rstudio"
      chapters: 
        - cap28.qmd             # Introducción a R y Rstudio, paquetes
        - s5_actividades1y2.qmd # Actividad: Miniresumen personal + foto para tu repositorio
        - cap29.qmd             # Introducción a Markdown
        - s5_actividades3.qmd   # Actividad: Crear tu página web
        - cap30.qmd             # introducción en Quarto
        - s5_actividades4y5.qmd # Actividad: Primer libro de quarto
    - part: "**Sección 6** - Introducción a Python"
      chapters: 
        - cap28.qmd
  appendices: 
    - resources.qmd
    - notas.qmd
  # Information
  repo-url: https://github.com/EveliaCoss/Mt2026_Taller_Computo_libro # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "flyer/logo.png" # icono de la pagina en pestana


format:
  html:
    crossrefs-hover: true
    footnotes-hover: true
    toc-depth: 4
    number-depth: 3
    # css
    css: styles.css
    linkcolor: "#007f99"
    
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      # dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    code-line-numbers: false #Numero de lineas
    code-annotations: hover #c(hover, below, select): posicion https://quarto.org/docs/authoring/code-annotation.html
    code-block-bg: true # Bloque de código
    code-block-border-left: "#007f99" # color del borde izquierdo del codigo
    syntax-highlighting: arrow # Estilo de los codigos https://quarto.org/docs/output-formats/html-code.html#highlighting
    freeze: false  # Desactivar congelamiento

editor: visual

bibliography: references.bib

lang: es

execute:
  error: true # Se aceptan errores
  message: false # Silenciar mensajes de salida
  echo: true

