project:
  type: book
  output-dir: docs #docs _book

book:
  title: "Taller de Cómputo"
  site-url: https://github.com/EveliaCoss/Mt2026_Taller_Computo_libro
  page-footer:  "Taller de Cómputo, 1er semestre: Dra. Evelia Coss" 
  sidebar: 
    # background: "#ffcccc"
    logo: "flyer/logo_enes.png" # Logo ENES
    search: true
  author: 
    - name: Evelia Coss
      degrees: PhD
      url: https://eveliacoss.github.io/ 
      orcid: https://orcid.org/0000-0002-7087-2977
      email: ecosnav@gmail.com
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: Mexico
          url: https://www.enesjuriquilla.unam.mx/
  
  date: "09/01/2026"
  page-navigation: true        # Provide next and previous article links in footer
  back-to-top-navigation: true # Provide a ‘back to top’ navigation button
  chapters:
    - index.qmd
    - temario.qmd
    - cap1A.qmd
    - evaluacion.qmd
    - part: "**Sección 1** - Componentes de una computadora"
      chapters:   
        - cap2A.qmd # Introducción - Componentes de una Computadora
        - game1.qmd
        - cap2B.qmd # Sistema Operativo (SO) y sus funciones
        - Tarea1.qmd # Tarea 1. Mi sistema operativo
        - cap3.qmd  # Buenas practicas en programacion 
        - udocz.qmd # Introducción del uso de Doc
        - s1_actividad1.qmd # Actividad 1 en equipo
    - part: "**Sección 2** - Instalación de programas"
      chapters: 
        - TodoLits.qmd # Lista de todas las aplicaciones      
        - install_B.qmd # Instalación de Git y Bash
        - install_R.qmd # Instalación de R, RStudio, Rtools /xcode
        - intro_R.qmd  # Introducción a R y Rstudio
        - install_python.qmd # python
        - integracion_bash_rstudio.qmd # Bash en terminal de Rstudio
    - part: "**Sección 3** - Introducción a Bash"
      chapters: 
        - cap4.qmd  # Introducción a Linux/Unix
        - cap5.qmd  # Mis primeros pasos en Bash   
        - cap6.qmd  # Wildcards y Streams
        - regex.qmd # REGEX
        - cap7.qmd  # Empleo de grep con REGEX
    - part: "**Sección 4** - Edición de archivos con Bash"
      chapters:     
        - cap8.qmd  # Edición de archivos con los editores de texto (nano y vim)
        - cap8_crearRproject.qmd # Crear Rproject e instalación de paquetes       
        - cap9.qmd  # Edición de archivos con el editor de flujo sed
        - cap10.qmd # Enlaces simbólicos (symlinks)
        - cap11.qmd # Filtrado de texto (grep, cut, sort, uniq, wc)
        - Bash_script.qmd # Mi primer bash script
        - s1_actividad2.qmd # Actividad 2 en equipo
        - cap12.qmd # Condicionales
        - cap14.qmd # Bucles (for loops)
    - part: "**Sección 5** - Introducción a Git/GitHub"
      chapters:
        - Rstudio_paquetes.qmd # Instalar paquetes      
        - cap15.qmd # Intro a Git
        - cap22.qmd # Conexión con Github
        - cap26.qmd # Conexión RStudio con Git         
        - cap16.qmd # Configurar git
        - Intro_Quarto.qmd
        - cap17.qmd # Crear e inicializar repos
        - cap18.qmd # Ignorar archivos
        - s5_actividades1y2.qmd # Actividad: Miniresumen personal + foto para tu repositorio
        - cap27.qmd # Resumen y practica final          
    - part: "**Sección 6** - Introducción a R y Rstudio"
      chapters: 
        - cap29.qmd             # Introducción a Markdown 
        - s5_actividades3.qmd   # Actividad: Crear tu página web
        - Intro_Quarto.qmd             # introducción en Quarto
        - s5_actividades4y5.qmd # Actividad: Primer libro de quarto
    - part: "**Sección 7** - Introducción a Python"
      chapters: 
        - s5_actividades4y5.qmd 
  appendices: 
    - resources.qmd
    - notas.qmd
    - docente.qmd
    - ejemplo_quizdown.qmd
    - ejemplo_CodeRandPython.qmd
  # Information
  repo-url: https://github.com/EveliaCoss/Mt2026_Taller_Computo_libro # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "flyer/logo.png" # icono de la pagina en pestana


format:
  html:
    crossrefs-hover: true # activa los popups al pasar el mouse sobre referencias cruzadas (secciones, figuras, tablas).
    footnotes-hover: true # muestra notas al pie como tooltip emergente.
    toc-depth: 4          # incluye encabezados hasta nivel ####.
    number-depth: 3
    filters:
      - focus-mode # https://lsbjordao.github.io/quarto-book-focus-mode-example/chapter-03.html
    # css
    css: styles.css
    linkcolor: "#007f99"
    # code
    engine: knitr
    live: true
    
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      # dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    code-line-numbers: false #Numero de lineas
    code-annotations: hover #c(hover, below, select): posicion https://quarto.org/docs/authoring/code-annotation.html
    code-block-bg: true # Bloque de código
    code-block-border-left: "#007f99" # color del borde izquierdo del codigo
    syntax-highlighting: arrow # Estilo de los codigos https://quarto.org/docs/output-formats/html-code.html#highlighting
    freeze: false  # Desactivar congelamiento

editor: visual

bibliography: references.bib

lang: es

execute:
  error: true # Se aceptan errores
  message: false # Silenciar mensajes de salida
  echo: true

