# Scripts en Bash

> **Fecha:** 29 de septiembre, 2026

Los `scripts` son archivos de texto que contienen instrucciones ejecutables por un intérprete de un lenguaje de programación para la ejecución de tareas. El formato `.sh` se utiliza para escribir `scripts ejecutables` por un intérprete como **Bash**. En esta sección crearemos varios scripts de Bash y usaremos varios comandos y operadores.

::: callout-note
Los script de Bash contiene al inicio esta descripción `#!bin/bash` y la extensión `.sh`
:::

## Actividad grupal

**Paso 1.** Crear un script en Bash con el nombre demo.sh empleando nano.

``` {.bash code-copy="true" eval="false"}
nano demo.sh
```

**Paso 2.** Copia el siguiente código dentro del script `demo.sh` y guarda los cambios.

``` {.bash code-copy="true" eval="false"}

#!/bin/bash
# File: demo.sh

# Variable local
curso="Bash básico"

# Variable de entorno
echo "Tu directorio HOME es: $HOME"

# Variables posicionales
echo "El nombre del script es: $0"
echo "El primer argumento es: $1"

# Variable especial
ls /noexiste
echo "El código de salida del último comando fue: $?"
```

::: {.callout-note collapse="true"}
## Explicación del código

- **Variables posicionales** Se usan en scripts para referirse a argumentos pasados al ejecutar.

  - `$0` → nombre del script.

  - `$1`, `$2`, … → primer, segundo argumento, etc.

  - `$#` → número de argumentos.

  - `$@` → todos los argumentos.

- **Variables especiales** Bash tiene variables internas con significados específicos:

  - `$?` → código de salida del último comando.

  - `$$` → PID del proceso actual.

  - `$!` → PID del último proceso en segundo plano.
:::

Este código realizará las siguientes instrucciones:

1.  Tomará como input el nombre del archivo `./_files/secuencias_bash.fastq` de secuencias fastq para analizar.

2.  Buscará dentro del archivo provisto por el usuario las secuencias con el string \@SRR098026 y las contará.

3.  Exportará las malas secuencias a un archivo llamado `malas_lecturas.fastq`, usando el string "NNNNNNNNNN" como plantilla.

4.  Reportará el número de malas secuencias.

5.  Luego buscaremos patrones en el archivo `buenas_lecturas.fastq`, si es que el usuario lo desea.

**Paso 3.** Deberías correr el script así, una vez que hayas descargado el archivo `secuencias_bash.fastq`:

``` {.bash code-copy="true" eval="false"}
bash demo.sh secuencias_bash.fastq
```

## Material suplementario

- RSG Ecuador. [Scripts en Bash](https://rsg-ecuador.github.io/unix.bioinfo.rsgecuador/content/Curso_avanzado/02_Bash/1_bash.html)
- RSG Ecuador. [Wildcards y Streams](https://rsg-ecuador.github.io/unix.bioinfo.rsgecuador/content/Curso_basico/03_Manejo_terminal/5_wildcards.html)
- RSG Ecuador. [Expresiones regulares (*regex*)](https://rsg-ecuador.github.io/unix.bioinfo.rsgecuador/content/Curso_basico/04_Procesamiento_ficheros_regex_pipes/3_Expresiones_regulares.html)
- [Wildcard Selection in Bash](https://pressbooks.senecapolytechnic.ca/uli101/chapter/wildcard-selection-in-bash/)
