---
title: "Development Indicators by Continent"
author: "Gapminder Analytics Group"
format: html
---

**Instalar Plotly directamente desde R** Usa el comando de reticulate:

```{r, eval=FALSE, echo=TRUE}
reticulate::py_install("plotly")
reticulate::py_install("pandas")
```

Esto instala Plotly en el mismo Python que viste en `repl_python`.

**Verificar instalación** Vuelve a entrar al REPL:

```{r, echo=TRUE}
reticulate::repl_python()
```

```{python}
import pandas as pd
import plotly.express as px

df = px.data.gapminder()
print(df.head())
```

Si ves las primeras filas del dataset, Pandas está funcionando correctamente.

## Row {height="60%"}

```{python}
#| title: GDP and Life Expectancy 

fig1 = px.scatter(  
  df, x="gdpPercap", y="lifeExp", 
  animation_frame="year", animation_group="country", 
  size="pop", color="continent", hover_name="country",
  facet_col="continent", log_x=True, size_max=45, 
  range_x=[100,100000], range_y=[25,90] 
)  

fig1.show()
```

## Row {height="40%"}

```{python}
#| title: Population
fig2 = px.area(
  df, x="year", y="pop", 
  color="continent", line_group="country"
)

fig2.show()
```

```{python}
#| title: Life Expectancy
fig3 = px.line(
  df, x="year", y="lifeExp", 
  color="continent", line_group="country"
)
fig3.show()
```
